AttendanceApp/Controllers/MyAttendanceController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AttendanceApp.DAL;
using AttendanceApp.Models;
using CrystalDecisions.CrystalReports.Engine;
using Newtonsoft.Json;
using PagedList;


namespace AttendanceApp.Controllers
{
    public class MyAttendanceController : Controller
    {
		// GET: MyAttendance


		private EmployeeDBContext db = new EmployeeDBContext();
		[Authorize]
		public ActionResult Index()
        {

			Employee userinfo = JsonConvert.DeserializeObject<Employee>(User.Identity.Name);
			int userID = Int32.Parse(userinfo.ID.ToString());

			List<Attendance> attendanceList =  db.Attendance.ToList().Where(x => x.EmployeeID == userID ).ToList();

		

			return View(attendanceList);
        }
		public ActionResult ExportCustomers()
		{
			List<Attendance> attendanceList = db.Attendance.ToList();

			foreach (var item in attendanceList)
			{
				item.TotalTime = "";
			}


			ReportDocument rd = new ReportDocument();
			rd.Load(Path.Combine(Server.MapPath("~/Reports"), "test.rpt"));

			rd.SetDataSource(attendanceList);

			Response.Buffer = false;
			Response.ClearContent();
			Response.ClearHeaders();


			Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
			stream.Seek(0, SeekOrigin.Begin);
			return File(stream, "application/pdf", "CustomerList.pdf");
		}
		public ActionResult All(int? page )
		{
			List<Employee> Employees = db.Employee.ToList();

			List<Attendance> attendanceList = db.Attendance.ToList();

		
			List<SelectListItem> listDD = new List<SelectListItem>();

			foreach(var e in Employees){
				listDD.Add(new SelectListItem
				{
					Value = e.ID.ToString(),
					Text = e.FirstName + e.LastName

				});

			}

			

			TempData["Employees"] = listDD;
			TempData["EmployeesNames"] = Employees;








			return View(attendanceList);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult All(int? Employee  , int? page, string start, string end)
		{
			

			List<Attendance> attendanceList;




			if (Employee != null)
			{

				if (start != "" && end != "")
				{


					DateTime dtstart = Convert.ToDateTime(start);
					DateTime dtend = Convert.ToDateTime(end);

					attendanceList = db.Attendance.ToList().Where(x => x.EmployeeID == Employee && x.DateOfDay >= dtstart && dtend >= x.DateOfDay).ToList();

				}
				else {

					attendanceList = db.Attendance.ToList().Where(x => x.EmployeeID == Employee).ToList();
				}
			
				//int userID = Int32.Parse(Employee);
			
			}
			else if (start != "" && end != "" && Employee == null)
			{

				DateTime dtstart = Convert.ToDateTime(start);
				DateTime dtend = Convert.ToDateTime(end);
				attendanceList = db.Attendance.ToList().Where(x => x.DateOfDay >= dtstart && dtend >= x.DateOfDay).ToList();

			}
			else {
				attendanceList = db.Attendance.ToList();
			}
		
			List<Employee> Employees = db.Employee.ToList();
			
			List<SelectListItem> listDD = new List<SelectListItem>();
			foreach (var e in Employees)
			{
				listDD.Add(new SelectListItem
				{
					Value = e.ID.ToString(),
					Text = e.FirstName +" "+ e.LastName

				});

			}
			TempData["Employees"] = listDD;
			TempData["EmployeesNames"] = Employees;
			TempData["Start"] = start;
			TempData["End"] = end;




			return View(attendanceList);
		}

			public ActionResult Edit(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Attendance attendance = db.Attendance.Find(id);
			if (attendance == null)
			{
				return HttpNotFound();
			}
			return View(attendance);
		}


		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(Attendance attendance)
		{
			if (ModelState.IsValid)
			{
				db.Entry(attendance).State = EntityState.Modified;
				db.SaveChanges();
				return RedirectToAction("Index");
			}
			return View(attendance);
		}


		public ActionResult Delete(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Attendance Attendance = db.Attendance.Find(id);
			if (Attendance == null)
			{
				return HttpNotFound();
			}
			return View(Attendance);
		}

		// POST: Employees/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public ActionResult DeleteConfirmed(int id)
		{
			Attendance Attendance = db.Attendance.Find(id);
			db.Attendance.Remove(Attendance);
			db.SaveChanges();
			return RedirectToAction("All");
		}



	}
}

AttendanceApp/Views/MyAttendance/All.cshtml
@model IEnumerable<AttendanceApp.Models.Attendance>
@using AttendanceApp.Models;
@using AttendanceApp.DAL;
@using PagedList.Mvc;



@{
	ViewBag.Title = "All";

	List<Employee> Employees = TempData["Employees"] as List<Employee>;
	string startDate = TempData["Start"] as string;
	string endDate = TempData["end"] as string;
}

<h2>Attendance</h2>



@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="row">
		<div class="form-group">
			<div class="col-md-12">
				Select Employee
			</div>
			</div>
		</div>
		<div class="row">
			<div class="form-group">

				<div class="col-md-3">
					@Html.DropDownList("Employee",
						(IEnumerable<SelectListItem>)TempData["Employees"],
						"All Employee",
						new { @class = "form-control", onchange = "this.form.submit();" })
				</div>
				<div class="col-md-3">
					<input id="start" name="start" class="form-control datapiker" placeholder="Start" value="@startDate" />
					
					</div>
				<div class="col-md-3">

					<input class="form-control datapiker"  id="end" name="end" placeholder="End" value="@endDate" />
				</div>

				<div class="col-md-3">

					<input type="submit" value="Search" class="btn btn-default" />
					</div>


				</div>
		</div>






			}




			<table class="table" style="margin-top:10px;">
				<tr>
					<th>
						@Html.DisplayNameFor(model => model.ComingTime)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.DateOfDay)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.LeaveTime)
					</th>
					<th>
						Employee Name
						</th>
<th></th>
				</tr>

				@foreach (var item in Model)
				{
					<tr>
						<td>
							@Html.DisplayFor(modelItem => item.ComingTime)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.DateOfDay)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.LeaveTime)
						</td>
						<td>
							@DispayEmployee(item.EmployeeID)

						</td>
						
						<td>
							

							@Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
						
							@Html.ActionLink("Delete", "Delete", new { id = item.ID })
						</td>
					</tr>
				}

			</table>



@section Scripts
{
	<script type="text/javascript">
        $(function () {
            $(".datapiker").datetimepicker({
                format: 'd/m/Y'
            });
        });

	</script>
}

@helper  DispayEmployee(int userID){


List<Employee> Employees = TempData["EmployeesNames"] as List<Employee>;
string username = "";

foreach (var E in Employees)
{

	if (E.ID == userID)
	{
		username = E.FirstName + " " + E.LastName;

	}



}


<span>
	@username

</span>


}

AttendanceApp/Views/MyAttendance/Delete.cshtml
@model AttendanceApp.Models.Attendance

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Attendance</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ComingTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ComingTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LeaveTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LeaveTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmployeeID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "MyAttendance")
        </div>
    }
</div>

AttendanceApp/Views/MyAttendance/Edit.cshtml
@model AttendanceApp.Models.Attendance

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Attendance</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.ComingTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ComingTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ComingTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LeaveTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LeaveTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LeaveTime, "", new { @class = "text-danger" })
            </div>
        </div>

		@Html.Hidden("EmployeeID")


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AttendanceApp/Views/MyAttendance/Index.cshtml
@model IEnumerable<AttendanceApp.Models.Attendance>

@using Newtonsoft.Json;
@using AttendanceApp.Models;
@using System;
@using System.Globalization;

<style>
    .paginate_button {
        padding: 6px 12px;
        background-color: white;
        margin-bottom: 0;
        margin-right: 2px;
        font-size: 14px;
        white-space: nowrap;
        font-weight: normal;
        color: #333;
        vertical-align: middle;
        -ms-touch-action: manipulation;
        touch-action: manipulation;
        cursor: pointer;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        background-image: none;
        border: 1px solid #5da75c;
        border-radius: 3px;
    }

    .disabled {
        cursor: not-allowed !important;
        filter: alpha(opacity=65);
        -webkit-box-shadow: none;
        box-shadow: none;
        opacity: .65;
    }

    .current {
        background-color: #5da75c !important;
        color: white !important;
    }
</style>

@{
    Employee userinfo = JsonConvert.DeserializeObject<Employee>(User.Identity.Name);
    ViewBag.Title = userinfo.FirstName;
    
}
@*<link href="~/Content/DataTables/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/DataTables/css/buttons.bootstrap.min.css" rel="stylesheet" />*@
<link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/buttons/1.6.1/css/buttons.dataTables.min.css" rel="stylesheet" />
<h2>My Attendance</h2>

<table class="table table-hover table-responsive table-bordered">
    <thead>
        <tr>


            <th>
                @Html.DisplayNameFor(model => model.DateOfDay)
            </th>
            <th>
                Day
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ComingTime)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.LeaveTime)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.TotalTime)
            </th>
            @{
                if (userinfo != null)
                {


                    if (userinfo.UserRoles == "Admin")
                    {
                        <th></th>

                    }


                }
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @item.DateOfDay.ToString("dd MMM yyyy")
                </td>
                <td>
                    @item.DateOfDay.DayOfWeek
                </td>
                <td>
                    @string.Format("{0:hh:mm:ss tt}", item.ComingTime)

                </td>

                <td>
                    @(item.LeaveTime != null ? string.Format("{0:hh:mm:ss tt}", item.LeaveTime) : "")
                </td>
                <td>
                    @item.TotalTime
                </td>

                @{
                    if (userinfo != null)
                    {


                        if (userinfo.UserRoles == "Admin")
                        {
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |

                                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                            </td>

                        }


                    }
                }


            </tr>
        }
    </tbody>

</table>



@helper DisplayTime(string time)
{



    DateTime dt = Convert.ToDateTime(time);


    <span>
        @dt.TimeOfDay.ToString()

    </span>


}

@section scripts{

    @*<script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/DataTables/buttons.bootstrap.min.js"></script>
    <script src="~/Scripts/DataTables/buttons.html5.min.js"></script>*@

    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.colVis.min.js"></script>
    <script>
        $("table").DataTable({
            dom: 'Bfrtip',
            buttons: [
                'copyHtml5',
                'excelHtml5',
                'csvHtml5',
                'pdfHtml5',
                'colvis'
            ]
        });


    </script>
}